### ISSUE TITLE
just some guidance please

### ISSUE THREAD

**Issue by mrs14t3r** [samuraitruong/coinmaster#17]
`{
  err: 'Failed to validate Session Token',
  hash: '8e643d5c2b8e72a46e65d8b7c617bc49'
}
`
this is not updated to latest version of web CM i'm guessing 
amazing work thank-you for making it open source.
any help would be appreciated

**Comment by samuraitruong** [comment]
Make sure you set FB_TOKEN in .env file, This is required and will be expired every 12 hours as I remember.

**Comment by mrs14t3r** [comment]
hi thanks for reply i have already tried this 
`#Global config
VERBOSE=0
TRACKING_EVENT=0
SLEEP=0
#default, random, revenge, friend, userId
#ATTACK_TARGET=random
# shield or coin
#ATTACK_PREFER=shield
AUTO_BET=true
MAX_AUTO_BET=3
RAID_AUTO_BET=30000000
QUEST_LEVEL_LIMIT=6
RAID_BET_SWITCH=30
ATTACK_BET_SWITCH=16
ATTACK_RAID_GAP=5
PRIORITY_UPGRADE=Ship
#update below information with your account
USER_ID=rof5__blahblah
FB_TOKEN=40f62e00320bc7061123
DEVICE_ID=fb109279103700678
DEVICE_CHANGE=20200924_8
AUTH_TOKEN:[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJkZXZpY2UiOnsiaWQiOiJmYjEwOTI3OTEwMzcwMDY3OCJ9LCJzZXNzaW9uIjp7InBsYXllcklkIjoicm9mNV9fY2p4azU4MnlzMDJzaGhkbGFibzV1ZmFqcCIsImV4dHJhIjp7InBsYXRmb3JtIjoiV2ViR0wiLCJwcm9maWxlIjoiM181X2Zid2ViX1Bvb2wifX0sImlhdCI6MTYwMTAxNDYwMSwiZXhwIjoxNjAxMDcyMjAxfQ.kTsWeJIbv8xOx9owh02O-ZKBB69KPU8H5xCGOn19NGk]
REWARDS_COUNT=3
ALLOw_UPGRADE=true
SYNC_TARGET=[useurid of player you want to give cards that you have]
`

maybe i am missing something 
still receive this error `jamies-MacBook-Pro:coinmsterauto-master jamie$ node index.js
Auto switcher at 30 16
Enemy target 
USER: rof5__ undefined
start socket server at port  3001
Error 409 Conflict https://vik-game.moonactive.net/api/v1/users/rof5__cjxk582ys02shhdlabo5ufajp/balance
{
  err: 'Failed to validate Session Token',
  hash: '8e643d5c2b8e72a46e65d8b7c617bc49'
}
(node:12152) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'seq' of null
    at CoinMaster.getBalance (/Users/jamie/Desktop/coinmsterauto-master/coinmaster.js:533:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CoinMaster.play (/Users/jamie/Desktop/coinmsterauto-master/coinmaster.js:828:15)
    at async /Users/jamie/Desktop/coinmsterauto-master/index.js:79:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:12152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by tonzsm** [comment]
> hi thanks for reply i have already tried this
> 
> `Global config
> VERBOSE=0
> TRACKING_EVENT=0
> SLEEP=0
> #default, random, revenge, friend, userId
> #ATTACK_TARGET=random
> 
> # shield or coin
> #ATTACK_PREFER=shield
> AUTO_BET=true
> MAX_AUTO_BET=3
> RAID_AUTO_BET=30000000
> QUEST_LEVEL_LIMIT=6
> RAID_BET_SWITCH=30
> ATTACK_BET_SWITCH=16
> ATTACK_RAID_GAP=5
> PRIORITY_UPGRADE=Ship
> #update below information with your account
> USER_ID=rof5__blahblah
> FB_TOKEN=40f62e00320bc7061123
> DEVICE_ID=fb109279103700678
> DEVICE_CHANGE=20200924_8
> AUTH_TOKEN:[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJkZXZpY2UiOnsiaWQiOiJmYjEwOTI3OTEwMzcwMDY3OCJ9LCJzZXNzaW9uIjp7InBsYXllcklkIjoicm9mNV9fY2p4azU4MnlzMDJzaGhkbGFibzV1ZmFqcCIsImV4dHJhIjp7InBsYXRmb3JtIjoiV2ViR0wiLCJwcm9maWxlIjoiM181X2Zid2ViX1Bvb2wifX0sImlhdCI6MTYwMTAxNDYwMSwiZXhwIjoxNjAxMDcyMjAxfQ.kTsWeJIbv8xOx9owh02O-ZKBB69KPU8H5xCGOn19NGk]
> REWARDS_COUNT=3
> ALLOw_UPGRADE=true
> SYNC_TARGET=[useurid of player you want to give cards that you have]
> `
> 
> maybe i am missing something
> still receive this error
> 
> `jamies-MacBook-Pro:coinmsterauto-master jamie$ node index.js Auto switcher at 30 16 Enemy target USER: rof5__ undefined start socket server at port 3001 Error 409 Conflict https://vik-game.moonactive.net/api/v1/users/rof5__/balance { err: 'Failed to validate Session Token', hash: '8e643d5c2b8e72a46e65d8b7c617bc49' } (node:12152) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'seq' of null at CoinMaster.getBalance (/Users/jamie/Desktop/coinmsterauto-master/coinmaster.js:533:29) at processTicksAndRejections (internal/process/task_queues.js:93:5) at async CoinMaster.play (/Users/jamie/Desktop/coinmsterauto-master/coinmaster.js:828:15) at async /Users/jamie/Desktop/coinmsterauto-master/index.js:79:21 (Use `node --trace-warnings ...`to show where the warning was created) (node:12152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3) (node:12152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Can you fix it yet? I have the same problem as you.

**Comment by samuraitruong** [comment]
your token doesn't seem valid, it should not need to wrap in "[]"

when I have time I will test the code again, because it was a very long time without any update not sure it still work

**Comment by tonzsm** [comment]
> your token doesn't seem valid, it should not need to wrap in "[]"
> 
> 
> 
> when I have time I will test the code again, because it was a very long time without any update not sure it still work

i have not “[]” in line, ok we wait you for test and update

**Comment by tonzsm** [comment]
i can fix it must edit "AUTH_TOKEN:"  to "AUTH_TOKEN=" in .env file @mrs14t3r

**Comment by mrs14t3r** [comment]
> i can fix it must edit "AUTH_TOKEN:" to "AUTH_TOKEN=" in .env file @mrs14t3r

Thanks will test when back home :)

**Comment by mrs14t3r** [comment]
> Make sure you set FB_TOKEN in .env file, This is required and will be expired every 12 hours as I remember.

worked :) plays game perfectly using this input

> i can fix it must edit "AUTH_TOKEN:" to "AUTH_TOKEN=" in .env file @mrs14t3r

**Comment by gteuk** [comment]
Is there another way to get the Auth token data as the coinmaster web app is down at the mo, I have looked through my android device also in the playerinfo file it gives gam and device id but no token data :( 
I was looking at maybe incorporating this into a discord bot to show raids and attacks on private server :O

**Comment by Exoc6072** [comment]
> > Make sure you set FB_TOKEN in .env file, This is required and will be expired every 12 hours as I remember.
> 
> worked :) plays game perfectly using this input
> 
> > i can fix it must edit "AUTH_TOKEN:" to "AUTH_TOKEN=" in .env file @mrs14t3r

Hi ! bro's i want to see your code because i'm newbie for this

**Comment by gteuk** [comment]
the code is how it is in the download 
I use visual studio code to run it 
Some knowledge of JS is needed to understand the errors it throws out 

I would love to integrate this with a chat bot I have but my knowledge is not that great but can read from the json files which is pretty cool so it shows what cards I got in whichever deck :D :D

**Comment by fameza123** [comment]
Is it possible to use a cookie or a token instead of receiving a value by pressing f12 I mean login auto and play?

**Comment by Exoc6072** [comment]
You can teach me for this bro ?

ในวันที่ พ. 4 พ.ย. 2020 เวลา 13:51 fameza123 <notifications@github.com>
เขียนว่า:

**Comment by samuraitruong** [comment]
@fameza123  No, CM api only accept token
