### ISSUE TITLE
Cannot find info

### ISSUE THREAD

**Issue by thangluu93** [samuraitruong/coinmaster#9]
Hello samuraitruong,
I cannot find UID,Device ID,...

**Comment by eltonyjefe** [comment]
De donde obtenemos esos datos?

**Comment by samuraitruong** [comment]
1. open game in facebook with chrome browser
2. Press F11 or select "Inspect"  and change to Network tab
3. Wait for the game load, you will see the API call, 
4. collect the UID, device ID from the request header

**Comment by eltonyjefe** [comment]
Hola. Gracias por contestar.
Encontré:
Fb_id
Id_device

No se cual es User_id

Donde lo encuentro?

Gracias
